import { FunctionComponent } from 'react'
import Head from 'next/head'

import BasicLayout from 'layout/BasicLayout'
import HeroSection from 'components/HeroSection'

interface BlogProps {}

const Blog: FunctionComponent<BlogProps> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <HeroSection
          title="Blog"
          small
          image="blog.jpg"
          smallImage="blog-small.jpg"
        />
      </BasicLayout>
    </div>
  )
}

export default Blog
