import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql } from '@apollo/client'

import BasicLayout from 'layout/BasicLayout'
import HeroSection from 'components/HeroSection'
import apolloClient from 'apolloClient'

interface HomeProps {
  title: string
  subtitle: string
  image: string
  smallImage: string
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <HeroSection
          title={props.title}
          subtitle={props.subtitle}
          image={props.image}
          smallImage={props.smallImage}
        />
      </BasicLayout>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  const data = (
    await apolloClient.query({
      query: gql`
        query GetHomePage {
          HomePage(id: "homePage") {
            _id
            title {
              en
              sk
            }
            subtitle {
              en
              sk
            }
            image {
              asset {
                url
              }
            }
          }
        }
      `
    })
  ).data['HomePage']

  return {
    props: {
      title: data.title[locale],
      subtitle: data.subtitle[locale],
      image: data.image.asset.url,
      smallImage: `${data.image.asset.url}?w=48`
    }
  }
}

export default Home
