import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import BasicLayout from 'layout/BasicLayout'
import HeroSection from 'components/HeroSection'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <HeroSection
          title="Explore, create, share"
          subtitle="Aliqua adipisicing ullamco pariatur laborum deserunt aliqua dolor anim et sint commodo reprehenderit magna eiusmod."
          image="hero-img.jpg"
          smallImage="hero-img-small.jpg"
        />
      </BasicLayout>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
